# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JWbyO1-neUX9_VivuwXJpILj_7Gt8AHz
"""

import streamlit as st
import pandas as pd
import random

# ----------------------------
# Page Setup
# ----------------------------
st.set_page_config(page_title="WizardVerse House Quiz", page_icon="🧙‍♂️", layout="wide")

# ----------------------------
# Define Colors and Backgrounds
# ----------------------------
house_themes = {
    "Gryffindor": {"color": "#740001", "bg": "https://i.imgur.com/Ns6h2CJ.jpg"},
    "Slytherin": {"color": "#1A472A", "bg": "https://i.imgur.com/dgZsfxL.jpg"},
    "Ravenclaw": {"color": "#222F5B", "bg": "https://i.imgur.com/wWVuJZX.jpg"},
    "Hufflepuff": {"color": "#EEE117", "bg": "https://i.imgur.com/G0b6v3B.jpg"},
}

# ----------------------------
# House Selection
# ----------------------------
st.title("🏰 Welcome to the WizardVerse Challenge!")
house = st.selectbox("Choose your Hogwarts House:", ["Gryffindor", "Slytherin", "Ravenclaw", "Hufflepuff"])

theme = house_themes[house]
st.markdown(f"<style>body{{background-color:{theme['color']};}}</style>", unsafe_allow_html=True)

st.markdown(f"### 🪄 Welcome, {house} Champion! Prepare for your unique magical challenge.")

# ----------------------------
# Load Data
# ----------------------------
dialogues = pd.read_csv('/content/Dialogue.csv', encoding='latin-1')
spells = pd.read_csv('/content/Spells.csv', encoding='latin-1')

# ----------------------------
# House-Specific Quizzes
# ----------------------------
if house == "Gryffindor":
    st.header("🦁 Battle of Wits")
    st.write("Answer fast! Prove your courage in these daring questions:")
    sample_dialogue = dialogues.sample(1).iloc[0]
    quote = sample_dialogue['dialogue']
    ans = sample_dialogue['character']
    user = st.text_input(f"Who said this quote? 💬  '{quote}'")
    if st.button("Check Answer"):
        if user.lower() == str(ans).lower():
            st.success(f"Brilliant! 🪄 You have the heart of a true Gryffindor!")
        else:
            st.error(f"Wrong! It was {ans}. Keep training, warrior.")

elif house == "Slytherin":
    st.header("🐍 Riddle of the Serpent")
    st.write("Decode this magical riddle to prove your cunning:")
    riddle = "I can make you invisible, but I’m not a spell. I’m a thing you wear, but not on your feet. What am I?"
    answer = "cloak"
    guess = st.text_input("Your Answer:")
    if st.button("Reveal Riddle"):
        if "cloak" in guess.lower():
            st.success("Impressive! You truly think like a Slytherin 🐍")
        else:
            st.error("Nope... Think again. It was the *Invisibility Cloak*.")

elif house == "Ravenclaw":
    st.header("🦅 Raven’s Riddle")
    st.write("Answer the hardest question in Hogwarts history:")
    st.write("What magical object shows your deepest desire?")
    guess = st.text_input("Your Answer:")
    if st.button("Submit Answer"):
        if "mirror of erised" in guess.lower():
            st.success("Correct! Wisdom truly lies within you 🦅")
        else:
            st.error("Incorrect! The answer was *Mirror of Erised*.")

elif house == "Hufflepuff":
    st.header("🦡 Magical Memory Match")
    st.write("Kindness shines through your knowledge. Match this spell to its effect:")
    row = spells.sample(1).iloc[0]
    effect = row['effect']
    name = row['spell']
    user_spell = st.text_input(f"What spell causes this effect? '{effect}'")
    if st.button("Reveal Spell"):
        if user_spell.lower() == str(name).lower():
            st.success(f"Correct! ✨ That’s {name}. You embody the heart of Hufflepuff!")
        else:
            st.error(f"Almost! It was {name}. Kindness and practice make perfect 💛")