# -*- coding: utf-8 -*-
"""wizardverse_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tXemuPd0BOKzSbSq74gBogA9VLq7aCgU
"""

import streamlit as st
import plotly.express as px
import pandas as pd
from pathlib import Path

# ---------------------- PAGE CONFIG ----------------------
st.set_page_config(
    page_title="WizardVerse AI Dashboard",
    layout="wide",
    page_icon="🪄"
)

# ---------------------- STYLING ----------------------
st.markdown("""
<style>
.stApp {
    background-image: url('assets/hogwarts_bg.jpg');
    background-size: cover;
    background-attachment: fixed;
    background-position: center;
}
.block-container {
    background: rgba(0,0,0,0.6);
    border-radius: 20px;
    padding: 2rem;
    color: white;
}
h1, h2, h3, h4 {
    color: #FFD700 !important;
    text-shadow: 1px 1px 3px black;
}
</style>
""", unsafe_allow_html=True)

# ---------------------- HEADER ----------------------
st.title("🪄 WizardVerse AI: Books vs Movies Dashboard")
st.markdown("### Explore magical insights from the Harry Potter universe — comparing books and movies using NLP & data science!")

# ---------------------- SIDEBAR ----------------------
st.sidebar.header("🔍 Filters")

house = st.sidebar.selectbox("🏰 Select House", ["All", "Gryffindor", "Slytherin", "Hufflepuff", "Ravenclaw"])
media_type = st.sidebar.selectbox("🎬 Select Media Type", ["Books", "Movies", "Both"])
sentiment_range = st.sidebar.slider("💫 Sentiment Range", -1.0, 1.0, (-1.0, 1.0))
character_list = ["Harry", "Hermione", "Ron", "Draco", "Dumbledore", "Snape"]
characters = st.sidebar.multiselect("🧙‍♂️ Select Characters", character_list, default=["Harry", "Hermione", "Ron"])

# ---------------------- LOAD SAMPLE DATA ----------------------
# Replace this with your real datasets
sentiment_df = pd.DataFrame({
    "Chapter": [f"Chapter {i}" for i in range(1, 11)],
    "Sentiment": [0.1, 0.4, -0.2, 0.3, 0.0, 0.6, -0.4, 0.2, 0.5, 0.1],
    "Media": ["Book"] * 5 + ["Movie"] * 5
})

character_sentiment_df = pd.DataFrame({
    "Character": ["Harry", "Hermione", "Ron", "Draco", "Snape"] * 2,
    "Sentiment": [0.5, 0.3, 0.1, -0.2, -0.4, 0.4, 0.2, 0.0, -0.1, -0.3],
    "Media": ["Book"] * 5 + ["Movie"] * 5
})

spells_df = pd.DataFrame({
    "Spell": ["Expelliarmus", "Lumos", "Avada Kedavra", "Alohomora", "Expecto Patronum"],
    "Count": [40, 25, 10, 20, 15],
    "Media": ["Book", "Book", "Movie", "Movie", "Book"]
})

# ---------------------- TABS ----------------------
tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "📚 Overview",
    "🧙‍♂️ Character Analysis",
    "💖 Sentiment Insights",
    "✨ Spells & Events",
    "🧩 Embedding Similarity"
])

# ---------------------- OVERVIEW TAB ----------------------
with tab1:
    st.subheader("📊 Overall Comparison between Books and Movies")
    col1, col2 = st.columns(2)
    with col1:
        fig = px.bar(sentiment_df, x="Chapter", y="Sentiment", color="Media", title="Sentiment per Chapter")
        st.plotly_chart(fig, use_container_width=True)
    with col2:
        word_counts = pd.DataFrame({"Media": ["Books", "Movies"], "Word Count": [120000, 80000]})
        fig2 = px.pie(word_counts, values="Word Count", names="Media", title="Word Count Comparison")
        st.plotly_chart(fig2, use_container_width=True)

# ---------------------- CHARACTER TAB ----------------------
with tab2:
    st.subheader("🧙 Character Sentiment Analysis")
    fig3 = px.box(character_sentiment_df, x="Character", y="Sentiment", color="Media", title="Character Sentiment Distribution")
    st.plotly_chart(fig3, use_container_width=True)

# ---------------------- SENTIMENT TAB ----------------------
with tab3:
    st.subheader("💫 Sentiment Trend across Chapters")
    fig4 = px.line(sentiment_df, x="Chapter", y="Sentiment", color="Media", markers=True)
    st.plotly_chart(fig4, use_container_width=True)

# ---------------------- SPELLS TAB ----------------------
with tab4:
    st.subheader("✨ Spell Frequency Analysis")
    fig5 = px.bar(spells_df, x="Spell", y="Count", color="Media", title="Spells Usage in Books vs Movies")
    st.plotly_chart(fig5, use_container_width=True)

# ---------------------- EMBEDDING TAB ----------------------
with tab5:
    st.subheader("🧩 Sentence Similarity Explorer")
    query = st.text_input("Enter a line or sentence from the Wizarding World:")
    if query:
        st.write("🔮 Top 3 most similar sentences (placeholder):")
        st.table(pd.DataFrame({
            "Similar Sentence": [
                "It’s leviosa, not leviosar!",
                "Happiness can be found even in the darkest of times.",
                "After all this time? Always."
            ],
            "Similarity Score": [0.89, 0.85, 0.80]
        }))